# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  quay:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: create README
        run: echo hello `date` > README.md

      # Runs a set of commands using the runners shell
      - name: push to quay
        run: |
          docker login quay.io -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_PASS }}
          docker pull hello-world
          docker tag hello-world quay.io/${{ secrets.QUAY_USER }}/my-repo:latest
          docker push quay.io/${{ secrets.QUAY_USER }}/my-repo:latest
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_APIKEY: ${{ secrets.DOCKER_APIKEY }}
        with:
          destination_container_repo: ${{ secrets.QUAY_USER }}/my-repo
          provider: quay
          readme_file: 'README.md'

